# Stage 1: Build the application (install dependencies)
FROM node:18-slim

WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package.json package-lock.json ./
RUN npm install
RUN npm install -g nodemon

COPY . .

# Expose the port the application listens on
EXPOSE 3000

# Command to run the application
CMD ["nodemon", "server.js"]