version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:${APP_PORT}"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/${MONGO_DB_NAME}?authSource=admin&directConnection=true
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - PORT=3000
    networks:
      - app-network
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:4.4.18
    ports:
      - "127.0.0.1:27017"
    volumes:
      - mongodb-configdb:/data/configdb
      - mongodb-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    networks:
      - app-network
    restart: unless-stopped


networks:
  app-network:
    driver: bridge

volumes:
  mongodb-configdb:
  mongodb-db:
